### ISSUE TITLE
Wrapper not using full libraries

### ISSUE THREAD

**Issue by erikeldh** [sillsdev/icu-dotnet#143] opened 2021-02-24 15:21 UTC
## Describe the bug
I keep getting the following exception even with the full libraries.
System.MissingMemberException: 'Do you have the full version of ICU installed? The method 'ubrk_open' is not included in the minimal version of ICU.'

## To Reproduce

Icu.Wrapper.Init();
var locale = new Icu.Locale("en_EN");
var test = Icu.BreakIterator.CreateWordInstance(locale);
test.SetText("The file could not be read:");

I get the exception on the last line.

## Environment
I have the following nuget packages installed via visual studio 16.8.4 windows 10 in a .net core 5 project:
icu.net 2.6.0
Icu4cWin.Full.Bin 59.1.15
Icu4cWin.Full.Lib 59.1.15

**Comment by ermshiperete** [comment] 2021-02-24 15:58
Make sure there is no icudt*.dll, icuin*.dll, icuio*.dll, icutu*.dll, or icuuc*.dll anywhere in a directory that is included in your PATH.

Also, where are these dlls relative to the output directory? They should be in `lib/win-*`.

Do you get the same crash with the latest pre-release versions of icu.net (2.7.0-beta.12) and Icu4c.Win.Full.* (62.2.1-beta).

Please create a console project where `Main()` contains your code snippet from above that demonstrates the problem. I tried with your code snippet and the nuget package versions you mentioned, but am not able to reproduce, so there's something else going on.

**Comment by ermshiperete** [comment] 2022-04-12 06:54
Closing this for now. Feel free to re-open with additional information.

**Closed by ermshiperete** 2022-04-12 06:54 UTC
Labels: needs more info
